package model;

public enum TipoPelicula {
	ACCION, DRAMA, COMEDIA, SUSPENSO, TERROR, CIENCIA_FICCION, ANIMACION, DOCUMENTAL, INFANTIL, ADULTOS, AVENTURA, RELIGIOSA, ANIME, COMIC, HISTORICA, MUSICAL;
}
